# Generated by Django 5.1.2 on 2025-12-01 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255)),
                ('regimen_fiscal', models.CharField(blank=True, max_length=100)),
                ('calle', models.CharField(blank=True, max_length=255)),
                ('numero_exterior', models.CharField(blank=True, max_length=20)),
                ('numero_interior', models.CharField(blank=True, max_length=20)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=5)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('representante_legal', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['razon_social'],
            },
        ),
    ]
