# Generated by Django 5.1.2 on 2025-12-02 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificaciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recibir_solicitudes', models.BooleanField(default=True, help_text='Notificar solicitudes pendientes de aprobación')),
                ('recibir_alertas', models.BooleanField(default=True, help_text='Alertas de vencimientos y recordatorios')),
                ('recibir_confirmaciones', models.BooleanField(default=True, help_text='Confirmaciones de acciones completadas')),
                ('recibir_nomina', models.BooleanField(default=True, help_text='Notificaciones de nómina y recibos')),
                ('frecuencia_email', models.CharField(choices=[('inmediato', 'Inmediato'), ('diario', 'Resumen Diario'), ('semanal', 'Resumen Semanal'), ('nunca', 'Nunca')], default='inmediato', max_length=20)),
                ('hora_envio', models.TimeField(default='09:00', help_text='Hora preferida para envío de resúmenes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
                'db_table': 'notificaciones_configuracion',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('solicitud', 'Solicitud de Aprobación'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('alerta', 'Alerta'), ('recordatorio', 'Recordatorio'), ('confirmacion', 'Confirmación'), ('nomina', 'Nómina'), ('documento', 'Documento'), ('sistema', 'Sistema')], max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('leida', 'Leída'), ('fallida', 'Fallida')], default='pendiente', max_length=15)),
                ('enviada_email', models.BooleanField(default=False)),
                ('fecha_envio_email', models.DateTimeField(blank=True, null=True)),
                ('error_envio', models.TextField(blank=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones_registro',
                'ordering': ['-created_at'],
            },
        ),
    ]
