# Generated by Django 5.1.2 on 2025-12-02 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_agregar_documento_empleado'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioDatos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_cambio', models.CharField(choices=[('rfc', 'RFC'), ('curp', 'CURP'), ('nss', 'Numero de Seguro Social'), ('cuenta_bancaria', 'Cuenta Bancaria'), ('direccion', 'Direccion'), ('telefono', 'Telefono'), ('email_personal', 'Email Personal'), ('contacto_emergencia', 'Contacto de Emergencia')], max_length=30)),
                ('datos_actuales', models.JSONField(default=dict, help_text='Datos actuales del empleado')),
                ('datos_nuevos', models.JSONField(default=dict, help_text='Datos nuevos solicitados')),
                ('justificacion', models.TextField(blank=True)),
                ('documento_soporte', models.FileField(blank=True, help_text='Documento de soporte (INE, comprobante, etc.)', null=True, upload_to='solicitudes_cambio/%Y/%m/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revision'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('comentario_revision', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='empleados.empleado')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Datos',
                'verbose_name_plural': 'Solicitudes de Cambio de Datos',
                'db_table': 'usuarios_solicitudes_cambio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tipo', models.CharField(choices=[('activacion', 'Activacion de Cuenta'), ('reset', 'Reset de Password')], max_length=20)),
                ('usado', models.BooleanField(default=False)),
                ('expira_en', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Usuario',
                'verbose_name_plural': 'Tokens de Usuario',
                'db_table': 'usuarios_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
