# Generated by Django 5.1.2 on 2025-12-01 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteIndividual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(max_length=50)),
                ('tipo_ajuste', models.CharField(choices=[('reemplaza', 'Reemplaza valor del plan'), ('suma', 'Suma al valor del plan')], max_length=20)),
                ('valor', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ajustes_individuales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanPrestaciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('es_default', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('vacaciones_dias_extra', models.PositiveIntegerField(default=0, help_text='Días adicionales sobre los de ley')),
                ('prima_vacacional_porcentaje', models.PositiveIntegerField(default=25, help_text='Porcentaje de prima vacacional')),
                ('aguinaldo_dias', models.PositiveIntegerField(default=15, help_text='Días de aguinaldo')),
            ],
            options={
                'db_table': 'planes_prestaciones',
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrestacionAdicional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_valor', models.CharField(choices=[('monto', 'Monto fijo'), ('porcentaje', 'Porcentaje del salario'), ('texto', 'Descripción')], max_length=20)),
                ('valor', models.CharField(max_length=100)),
                ('periodicidad', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual'), ('unica', 'Única vez')], default='mensual', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'prestaciones_adicionales',
                'ordering': ['plan', 'orden', 'nombre'],
            },
        ),
    ]
