# Generated by Django 5.1.2 on 2025-12-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestaciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestacionadicional',
            options={'ordering': ['plan', 'categoria', 'orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='prestacionadicional',
            name='aplica_a_dependientes',
            field=models.BooleanField(default=False, help_text='Si la prestacion aplica a familiares/dependientes'),
        ),
        migrations.AddField(
            model_name='prestacionadicional',
            name='categoria',
            field=models.CharField(choices=[('economica', 'Economica'), ('salud', 'Salud y Bienestar'), ('tiempo', 'Tiempo y Flexibilidad'), ('desarrollo', 'Desarrollo y Educacion'), ('familia', 'Familia'), ('otro', 'Otro')], default='otro', help_text='Categoria de la prestacion', max_length=20),
        ),
        migrations.AddField(
            model_name='prestacionadicional',
            name='numero_dependientes',
            field=models.PositiveIntegerField(blank=True, help_text='Numero maximo de dependientes cubiertos', null=True),
        ),
        migrations.AddField(
            model_name='prestacionadicional',
            name='porcentaje_empleado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje que aporta el empleado', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prestacionadicional',
            name='porcentaje_empresa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje que aporta la empresa', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prestacionadicional',
            name='proveedor',
            field=models.CharField(blank=True, help_text='Nombre del proveedor (aseguradora, empresa de vales, etc.)', max_length=200),
        ),
        migrations.AddField(
            model_name='prestacionadicional',
            name='tipo_prestacion',
            field=models.CharField(blank=True, choices=[('vales_despensa', 'Vales de despensa'), ('fondo_ahorro', 'Fondo de ahorro'), ('bono_productividad', 'Bono de productividad'), ('bono_puntualidad', 'Bono de puntualidad'), ('bono_asistencia', 'Bono de asistencia'), ('ayuda_transporte', 'Ayuda de transporte'), ('ayuda_comedor', 'Ayuda de comedor'), ('caja_ahorro', 'Caja de ahorro'), ('sgmm', 'Seguro de Gastos Medicos Mayores'), ('seguro_vida', 'Seguro de vida'), ('seguro_dental', 'Seguro dental'), ('seguro_vision', 'Seguro de vision'), ('checkup_medico', 'Check-up medico anual'), ('apoyo_psicologico', 'Apoyo psicologico'), ('gimnasio', 'Gimnasio'), ('vacaciones_extra', 'Dias de vacaciones adicionales'), ('dia_cumpleanos', 'Dia de cumpleanos libre'), ('dias_personales', 'Dias personales'), ('home_office', 'Home office'), ('horario_flexible', 'Horario flexible'), ('viernes_corto', 'Viernes corto'), ('beca_educativa', 'Beca educativa'), ('cursos_certificaciones', 'Cursos y certificaciones'), ('clases_idiomas', 'Clases de idiomas'), ('guarderia', 'Apoyo de guarderia'), ('beca_hijos', 'Beca para hijos'), ('licencia_paternidad_ext', 'Licencia de paternidad extendida'), ('licencia_maternidad_ext', 'Licencia de maternidad extendida'), ('auto_empresarial', 'Auto empresarial'), ('estacionamiento', 'Estacionamiento'), ('telefono_celular', 'Telefono celular'), ('laptop_equipo', 'Laptop/Equipo de trabajo'), ('prestamo_personal', 'Prestamo personal'), ('canasta_navidena', 'Canasta navidena'), ('otro', 'Otro')], help_text='Tipo predefinido del catalogo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prestacionadicional',
            name='tope_anual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tope maximo anual en pesos', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='prestacionadicional',
            name='tope_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tope maximo mensual en pesos', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='prestacionadicional',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripcion detallada de la prestacion'),
        ),
        migrations.AlterField(
            model_name='prestacionadicional',
            name='periodicidad',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual'), ('unica', 'Unica vez')], default='mensual', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestacionadicional',
            name='tipo_valor',
            field=models.CharField(choices=[('monto', 'Monto fijo'), ('porcentaje', 'Porcentaje del salario'), ('texto', 'Descripcion')], max_length=20),
        ),
    ]
