# Generated by Django 5.1.2 on 2025-12-01 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Indefinido'), ('temporal', 'Temporal'), ('obra', 'Por obra determinada'), ('tiempo', 'Por tiempo determinado'), ('capacitacion', 'Capacitación inicial'), ('prueba', 'Periodo de prueba')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('salario_diario', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('condiciones_especiales', models.TextField(blank=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('renovado', 'Renovado'), ('cancelado', 'Cancelado')], default='vigente', max_length=20)),
                ('contrato_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovacion', to='contratos.contrato')),
            ],
            options={
                'db_table': 'contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
