# Generated by Django 5.1.2 on 2025-12-03 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='alerta_enviada_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='alerta_enviada_30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='alerta_enviada_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='clausulas_adicionales',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contrato',
            name='documento_firmado',
            field=models.FileField(blank=True, null=True, upload_to='contratos/firmados/'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_firma',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_terminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='horario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contrato',
            name='jornada',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contrato',
            name='motivo_terminacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='salario_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='contratos.contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('renovado', 'Renovado'), ('cancelado', 'Cancelado'), ('terminado', 'Terminado')], default='vigente', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('indefinido', 'Indefinido'), ('temporal', 'Temporal'), ('obra', 'Por obra determinada'), ('tiempo', 'Por tiempo determinado'), ('capacitacion', 'Capacitacion inicial'), ('prueba', 'Periodo de prueba')], max_length=20),
        ),
        migrations.CreateModel(
            name='Adenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('cambio_salario', 'Cambio de Salario'), ('cambio_puesto', 'Cambio de Puesto'), ('cambio_horario', 'Cambio de Horario'), ('cambio_departamento', 'Cambio de Departamento'), ('extension', 'Extension de Contrato'), ('condiciones', 'Cambio de Condiciones'), ('otro', 'Otro')], max_length=30)),
                ('fecha_aplicacion', models.DateField()),
                ('descripcion', models.TextField()),
                ('valores_anteriores', models.JSONField(blank=True, default=dict)),
                ('valores_nuevos', models.JSONField(blank=True, default=dict)),
                ('documento', models.FileField(blank=True, null=True, upload_to='contratos/adendas/')),
                ('aplicada', models.BooleanField(default=False)),
                ('fecha_aplicada', models.DateTimeField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adendas', to='contratos.contrato')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contratos_adendas',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
