# Generated by Django 5.1.2 on 2025-12-01 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoDispersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to='dispersion/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('total_registros', models.IntegerField(default=0)),
                ('total_importe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('enviado', 'Enviado al Banco'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('parcial', 'Parcialmente Aplicado'), ('rechazado', 'Rechazado')], default='generado', max_length=20)),
                ('referencia_banco', models.CharField(blank=True, max_length=100)),
                ('fecha_aplicacion', models.DateTimeField(blank=True, null=True)),
                ('registros_aplicados', models.IntegerField(default=0)),
                ('registros_rechazados', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Archivo de Dispersión',
                'verbose_name_plural': 'Archivos de Dispersión',
                'db_table': 'integraciones_archivo_dispersion',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionBanco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenta_origen', models.CharField(max_length=20)),
                ('clabe_origen', models.CharField(max_length=18)),
                ('formato_layout', models.CharField(choices=[('spei', 'SPEI Estándar'), ('banamex', 'Banamex'), ('bancomer', 'BBVA'), ('santander', 'Santander'), ('banorte', 'Banorte'), ('hsbc', 'HSBC')], default='spei', max_length=50)),
                ('directorio_layouts', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Configuración Banco',
                'db_table': 'integraciones_config_banco',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionIntegracion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('usuario', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('certificado_cer', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('certificado_key', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('password_key', models.CharField(blank=True, max_length=200)),
                ('modo_sandbox', models.BooleanField(default=True, help_text='True = ambiente de pruebas, False = producción')),
                ('configuracion_extra', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True)),
                ('estado_conexion', models.CharField(choices=[('no_verificado', 'No Verificado'), ('conectado', 'Conectado'), ('error', 'Error de Conexión')], default='no_verificado', max_length=20)),
                ('ultimo_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuración de Integración',
                'verbose_name_plural': 'Configuraciones de Integración',
                'db_table': 'integraciones_configuracion',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionPAC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfc_emisor', models.CharField(max_length=13)),
                ('regimen_fiscal', models.CharField(max_length=3)),
                ('lugar_expedicion', models.CharField(help_text='Código postal', max_length=5)),
                ('serie_nomina', models.CharField(default='N', max_length=25)),
                ('folio_actual', models.IntegerField(default=1)),
                ('generar_pdf', models.BooleanField(default=True)),
                ('enviar_email_empleado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuración PAC',
                'db_table': 'integraciones_config_pac',
            },
        ),
        migrations.CreateModel(
            name='LogIntegracion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('request_url', models.URLField(blank=True)),
                ('request_method', models.CharField(default='POST', max_length=10)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.TextField(blank=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('exitoso', 'Exitoso'), ('error', 'Error'), ('reintentando', 'Reintentando')], default='pendiente', max_length=20)),
                ('mensaje_error', models.TextField(blank=True)),
                ('tiempo_respuesta_ms', models.IntegerField(blank=True, null=True)),
                ('intentos', models.IntegerField(default=1)),
                ('referencia_tipo', models.CharField(blank=True, max_length=50)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de Integración',
                'verbose_name_plural': 'Logs de Integración',
                'db_table': 'integraciones_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorIntegracion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('pac', 'PAC (Timbrado CFDI)'), ('banco', 'Banco (Dispersión)'), ('imss', 'IMSS/SUA'), ('sat', 'SAT'), ('storage', 'Almacenamiento'), ('email', 'Email'), ('sms', 'SMS'), ('ia', 'Inteligencia Artificial')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('api_url_produccion', models.URLField(blank=True)),
                ('api_url_sandbox', models.URLField(blank=True)),
                ('url_documentacion', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor de Integración',
                'verbose_name_plural': 'Proveedores de Integración',
                'db_table': 'integraciones_proveedor',
            },
        ),
        migrations.CreateModel(
            name='WebhookEntrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('firma_valida', models.BooleanField(blank=True, null=True)),
                ('procesado', models.BooleanField(default=False)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('resultado_procesamiento', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Webhook Entrada',
                'verbose_name_plural': 'Webhooks Entrada',
                'db_table': 'integraciones_webhook',
                'ordering': ['-created_at'],
            },
        ),
    ]
