# Generated by Django 5.1.2 on 2025-12-01 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('integraciones', '0001_initial'),
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivodispersion',
            name='periodo_nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_dispersion', to='nomina.periodonomina'),
        ),
        migrations.AddField(
            model_name='archivodispersion',
            name='config_banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='integraciones.configuracionbanco'),
        ),
        migrations.AddField(
            model_name='configuracionintegracion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integraciones', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='configuracionbanco',
            name='configuracion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_banco', to='integraciones.configuracionintegracion'),
        ),
        migrations.AddField(
            model_name='configuracionpac',
            name='configuracion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_pac', to='integraciones.configuracionintegracion'),
        ),
        migrations.AddField(
            model_name='logintegracion',
            name='configuracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integraciones.configuracionintegracion'),
        ),
        migrations.AddField(
            model_name='configuracionintegracion',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones', to='integraciones.proveedorintegracion'),
        ),
        migrations.AddField(
            model_name='webhookentrada',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='integraciones.proveedorintegracion'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracionintegracion',
            unique_together={('empresa', 'proveedor')},
        ),
    ]
