# Generated by Django 5.1.2 on 2025-12-02 19:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('empleados', '0004_agregar_documento_empleado'),
        ('empresas', '0002_initial'),
        ('integraciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGoogleCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credentials_json', models.TextField(blank=True, help_text='Credenciales OAuth JSON')),
                ('refresh_token', models.TextField(blank=True)),
                ('calendar_id', models.CharField(blank=True, default='primary', help_text='ID del calendario (default: primary)', max_length=255)),
                ('sincronizar_vacaciones', models.BooleanField(default=True)),
                ('sincronizar_cumpleanos', models.BooleanField(default=True)),
                ('sincronizar_aniversarios', models.BooleanField(default=True)),
                ('sincronizar_incapacidades', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('error_ultimo', models.TextField(blank=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_google_calendar', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuracion Google Calendar',
                'verbose_name_plural': 'Configuraciones Google Calendar',
                'db_table': 'integraciones_google_calendar',
            },
        ),
        migrations.CreateModel(
            name='EventoSincronizado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('cumpleanos', 'Cumpleanos'), ('aniversario', 'Aniversario Laboral'), ('incapacidad', 'Incapacidad'), ('otro', 'Otro')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('todo_el_dia', models.BooleanField(default=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255)),
                ('google_calendar_id', models.CharField(blank=True, max_length=255)),
                ('sincronizado', models.BooleanField(default=False)),
                ('fecha_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to='empleados.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_sincronizados', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Evento Sincronizado',
                'verbose_name_plural': 'Eventos Sincronizados',
                'db_table': 'integraciones_eventos_sincronizados',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('modificar', 'Modificar'), ('eliminar', 'Eliminar'), ('consultar', 'Consultar'), ('login', 'Inicio de Sesion'), ('logout', 'Cierre de Sesion'), ('exportar', 'Exportar'), ('aprobar', 'Aprobar'), ('rechazar', 'Rechazar')], max_length=20)),
                ('descripcion', models.TextField()),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'db_table': 'auditoria_registros',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', '-created_at'], name='auditoria_r_usuario_371c13_idx'), models.Index(fields=['content_type', 'object_id'], name='auditoria_r_content_bdf7a2_idx'), models.Index(fields=['accion', '-created_at'], name='auditoria_r_accion_fc1c8c_idx')],
            },
        ),
    ]
