# Generated by Django 5.1.2 on 2025-12-01 23:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_initial'),
        ('empresas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoKPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('ventas', 'Ventas'), ('productividad', 'Productividad'), ('calidad', 'Calidad'), ('servicio', 'Servicio al Cliente'), ('financiero', 'Financiero'), ('operativo', 'Operativo'), ('desarrollo', 'Desarrollo Personal'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('tipo_medicion', models.CharField(choices=[('numero', 'Número'), ('porcentaje', 'Porcentaje'), ('moneda', 'Moneda'), ('boolean', 'Sí/No'), ('escala', 'Escala (1-10)')], max_length=20)),
                ('unidad', models.CharField(blank=True, help_text='Ej: pesos, unidades, %, etc.', max_length=50)),
                ('frecuencia', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_excelente', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('es_mayor_mejor', models.BooleanField(default=True, help_text='Si es True, mayor valor = mejor desempeño')),
                ('activo', models.BooleanField(default=True)),
                ('aplica_a_puestos', models.JSONField(blank=True, default=list, help_text='Lista de puestos a los que aplica')),
                ('aplica_a_departamentos', models.JSONField(blank=True, default=list)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis_creados', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, help_text='Si es nulo, es un KPI global disponible para todas las empresas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_kpis', to='empresas.empresa')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI del Catálogo',
                'verbose_name_plural': 'Catálogo de KPIs',
                'db_table': 'desempeno_catalogo_kpis',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionKPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_personalizado', models.CharField(blank=True, max_length=200)),
                ('descripcion_personalizada', models.TextField(blank=True)),
                ('tipo_medicion', models.CharField(blank=True, choices=[('numero', 'Número'), ('porcentaje', 'Porcentaje'), ('moneda', 'Moneda'), ('boolean', 'Sí/No'), ('escala', 'Escala (1-10)')], max_length=20)),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('periodo', models.CharField(help_text='Ej: 2024-Q4, 2024-12, 2024', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('meta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('peso', models.DecimalField(decimal_places=2, default=100, help_text='Peso porcentual en la evaluación total (0-100)', max_digits=5)),
                ('es_mayor_mejor', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('pendiente', 'Pendiente de Aprobación'), ('evaluado', 'Evaluado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('valor_logrado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('porcentaje_cumplimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cambios_pendientes', models.JSONField(blank=True, help_text='Cambios propuestos por el empleado pendientes de aprobación', null=True)),
                ('fecha_solicitud_cambio', models.DateTimeField(blank=True, null=True)),
                ('motivo_cambio', models.TextField(blank=True)),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis_asignados_a_otros', to='empleados.empleado')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis_asignados', to='empleados.empleado')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('kpi_catalogo', models.ForeignKey(blank=True, help_text='Opcional si es KPI personalizado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='desempeno.catalogokpi')),
            ],
            options={
                'verbose_name': 'KPI Asignado',
                'verbose_name_plural': 'KPIs Asignados',
                'db_table': 'desempeno_asignacion_kpis',
                'ordering': ['-fecha_inicio', 'empleado'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAvanceKPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='desempeno/evidencias/')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='desempeno.asignacionkpi')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Registro de Avance',
                'verbose_name_plural': 'Registros de Avance',
                'db_table': 'desempeno_registro_avances',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('prueba', 'Periodo de Prueba')], max_length=20)),
                ('periodo', models.CharField(help_text='Ej: 2024-Q4, 2024', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('puntuacion_kpis', models.DecimalField(blank=True, decimal_places=2, help_text='Promedio ponderado de KPIs (0-100)', max_digits=5, null=True)),
                ('puntuacion_competencias', models.DecimalField(blank=True, decimal_places=2, help_text='Evaluación de competencias (0-100)', max_digits=5, null=True)),
                ('puntuacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('logros', models.TextField(blank=True, help_text='Principales logros del periodo')),
                ('areas_mejora', models.TextField(blank=True, help_text='Áreas de oportunidad')),
                ('retroalimentacion_evaluador', models.TextField(blank=True)),
                ('retroalimentacion_empleado', models.TextField(blank=True)),
                ('plan_desarrollo', models.TextField(blank=True, help_text='Plan de desarrollo para siguiente periodo')),
                ('objetivos_siguientes', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_progreso', 'En Progreso'), ('pendiente_revision', 'Pendiente de Revisión'), ('completada', 'Completada'), ('cerrada', 'Cerrada')], default='borrador', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('firmado_evaluador', models.BooleanField(default=False)),
                ('firmado_empleado', models.BooleanField(default=False)),
                ('fecha_firma_evaluador', models.DateTimeField(blank=True, null=True)),
                ('fecha_firma_empleado', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='empleados.empleado')),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to='empleados.empleado')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación de Desempeño',
                'verbose_name_plural': 'Evaluaciones de Desempeño',
                'db_table': 'desempeno_evaluaciones',
                'ordering': ['-fecha_fin', 'empleado'],
                'unique_together': {('empleado', 'tipo', 'periodo')},
            },
        ),
    ]
