# Generated by Django 5.1.2 on 2025-12-03 11:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desempeno', '0001_initial'),
        ('empleados', '0004_agregar_documento_empleado'),
        ('empresas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='autoevaluacion_comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='autoevaluacion_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='autoevaluacion_puntuacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='clasificacion_desempeno',
            field=models.CharField(blank=True, help_text='bajo/medio/alto', max_length=10),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='clasificacion_potencial',
            field=models.CharField(blank=True, help_text='bajo/medio/alto', max_length=10),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='incluye_autoevaluacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='incluye_pares',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='incluye_subordinados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='modalidad',
            field=models.CharField(default='90', help_text='90=solo jefe, 180=jefe+auto, 360=todos', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='percentil',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='ranking_departamento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CatalogoCompetencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('liderazgo', 'Liderazgo'), ('comunicacion', 'Comunicacion'), ('trabajo_equipo', 'Trabajo en Equipo'), ('resultados', 'Orientacion a Resultados'), ('innovacion', 'Innovacion y Creatividad'), ('adaptabilidad', 'Adaptabilidad'), ('tecnica', 'Competencia Tecnica'), ('servicio', 'Servicio al Cliente'), ('etica', 'Etica e Integridad'), ('otro', 'Otro')], max_length=20)),
                ('nivel_1_descripcion', models.TextField(blank=True, help_text='Basico/En desarrollo')),
                ('nivel_2_descripcion', models.TextField(blank=True, help_text='Competente')),
                ('nivel_3_descripcion', models.TextField(blank=True, help_text='Avanzado')),
                ('nivel_4_descripcion', models.TextField(blank=True, help_text='Experto')),
                ('nivel_5_descripcion', models.TextField(blank=True, help_text='Referente/Mentor')),
                ('aplica_a_puestos', models.JSONField(blank=True, default=list)),
                ('aplica_a_niveles', models.JSONField(blank=True, default=list, help_text='Niveles jerarquicos')),
                ('es_obligatoria', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, help_text='Si es nulo, es global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_competencias', to='empresas.empresa')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Catalogo de Competencias',
                'db_table': 'desempeno_catalogo_competencias',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCompetencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nivel_esperado', models.PositiveSmallIntegerField(default=3, help_text='Nivel esperado 1-5')),
                ('nivel_obtenido', models.PositiveSmallIntegerField(blank=True, help_text='Nivel logrado 1-5', null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('ejemplos_conducta', models.TextField(blank=True, help_text='Ejemplos observados')),
                ('evaluador_tipo', models.CharField(blank=True, help_text='jefe/par/subordinado/autoevaluacion', max_length=20)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='desempeno.catalogocompetencia')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias_evaluadas', to='desempeno.evaluacion')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_evaluadas_a_otros', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Evaluacion de Competencia',
                'verbose_name_plural': 'Evaluaciones de Competencias',
                'db_table': 'desempeno_evaluacion_competencias',
            },
        ),
        migrations.CreateModel(
            name='RetroalimentacionContinua',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('reconocimiento', 'Reconocimiento'), ('mejora', 'Area de Mejora'), ('coaching', 'Coaching'), ('objetivo', 'Seguimiento de Objetivo'), ('general', 'General')], max_length=20)),
                ('contenido', models.TextField()),
                ('es_privado', models.BooleanField(default=False, help_text='Solo visible para RRHH y jefe')),
                ('requiere_seguimiento', models.BooleanField(default=False)),
                ('seguimiento_completado', models.BooleanField(default=False)),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retroalimentaciones_dadas', to='empleados.empleado')),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='desempeno.catalogocompetencia')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentaciones', to='empleados.empleado')),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='desempeno.asignacionkpi')),
            ],
            options={
                'verbose_name': 'Retroalimentacion',
                'verbose_name_plural': 'Retroalimentaciones',
                'db_table': 'desempeno_retroalimentacion',
                'ordering': ['-created_at'],
            },
        ),
    ]
