# Generated by Django 5.1.2 on 2025-12-01 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_initial'),
        ('empresas', '0002_initial'),
        ('nomina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='periodonomina',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodonomina',
            name='calculado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_calculados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodonomina',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_nomina', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='incidencianomina',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='nomina.periodonomina'),
        ),
        migrations.AddField(
            model_name='recibonomina',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos_nomina', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='recibonomina',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='nomina.periodonomina'),
        ),
        migrations.AddField(
            model_name='detallerecibonomina',
            name='recibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nomina.recibonomina'),
        ),
        migrations.AlterUniqueTogether(
            name='tablaisr',
            unique_together={('año', 'periodicidad', 'limite_inferior')},
        ),
        migrations.AlterUniqueTogether(
            name='tablasubsidio',
            unique_together={('año', 'periodicidad', 'limite_inferior')},
        ),
        migrations.AlterUniqueTogether(
            name='periodonomina',
            unique_together={('empresa', 'tipo_periodo', 'numero_periodo', 'año')},
        ),
        migrations.AlterUniqueTogether(
            name='recibonomina',
            unique_together={('periodo', 'empleado')},
        ),
        migrations.AlterUniqueTogether(
            name='detallerecibonomina',
            unique_together={('recibo', 'concepto')},
        ),
    ]
