# Generated by Django 5.1.2 on 2025-12-01 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('curp', models.CharField(blank=True, max_length=18)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('nss_imss', models.CharField(blank=True, max_length=11)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('estado_civil', models.CharField(blank=True, max_length=30)),
                ('telefono_personal', models.CharField(blank=True, max_length=20)),
                ('email_personal', models.EmailField(blank=True, max_length=254)),
                ('email_corporativo', models.EmailField(blank=True, max_length=254)),
                ('direccion_calle', models.CharField(blank=True, max_length=255)),
                ('direccion_numero', models.CharField(blank=True, max_length=20)),
                ('direccion_colonia', models.CharField(blank=True, max_length=100)),
                ('direccion_cp', models.CharField(blank=True, max_length=5)),
                ('direccion_municipio', models.CharField(blank=True, max_length=100)),
                ('direccion_estado', models.CharField(blank=True, max_length=50)),
                ('emergencia_nombre', models.CharField(blank=True, max_length=255)),
                ('emergencia_parentesco', models.CharField(blank=True, max_length=50)),
                ('emergencia_telefono', models.CharField(blank=True, max_length=20)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('clabe', models.CharField(blank=True, max_length=18)),
                ('fecha_ingreso', models.DateField()),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('indefinido', 'Indefinido'), ('temporal', 'Temporal'), ('obra', 'Por obra determinada'), ('tiempo', 'Por tiempo determinado'), ('capacitacion', 'Capacitación inicial'), ('prueba', 'Periodo de prueba')], max_length=20)),
                ('jornada', models.CharField(blank=True, choices=[('diurna', 'Diurna'), ('nocturna', 'Nocturna'), ('mixta', 'Mixta')], max_length=20)),
                ('modalidad', models.CharField(default='presencial', max_length=20)),
                ('salario_diario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('baja', 'Baja'), ('incapacidad', 'Incapacidad')], default='activo', max_length=20)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleados/fotos/')),
            ],
            options={
                'db_table': 'empleados',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
    ]
