# Generated by Django 5.1.2 on 2025-12-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_ultimo_dia_laborado',
            field=models.DateField(blank=True, help_text='Último día que el empleado trabajó efectivamente', null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='liquidacion_pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='monto_liquidacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto total de liquidación/finiquito pagado', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_baja',
            field=models.CharField(blank=True, choices=[('renuncia_voluntaria', 'Renuncia Voluntaria'), ('despido_justificado', 'Despido Justificado'), ('despido_injustificado', 'Despido Injustificado'), ('termino_contrato', 'Término de Contrato'), ('jubilacion', 'Jubilación'), ('fallecimiento', 'Fallecimiento'), ('mutuo_acuerdo', 'Mutuo Acuerdo'), ('otro', 'Otro')], max_length=30, null=True),
        ),
    ]
