# Generated by Django 5.1.2 on 2025-12-02 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_agregar_documento_empleado'),
        ('empleados', '0003_empleado_fecha_ultimo_dia_laborado_and_more'),
        ('nomina', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmpleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ine', 'INE/IFE'), ('curp', 'CURP'), ('rfc', 'Constancia RFC'), ('comprobante_domicilio', 'Comprobante de Domicilio'), ('acta_nacimiento', 'Acta de Nacimiento'), ('nss', 'Número de Seguro Social'), ('foto', 'Fotografía'), ('contrato', 'Contrato Laboral'), ('alta_imss', 'Alta IMSS'), ('mod_salario', 'Modificación de Salario IMSS'), ('carta_renuncia', 'Carta de Renuncia'), ('carta_despido', 'Carta de Despido'), ('finiquito', 'Finiquito'), ('constancia', 'Constancia Laboral'), ('incapacidad', 'Incapacidad IMSS'), ('permiso', 'Permiso/Justificante'), ('acta_admin', 'Acta Administrativa'), ('recibo', 'Recibo de Nómina'), ('cfdi', 'CFDI Nómina'), ('evaluacion', 'Evaluación de Desempeño'), ('capacitacion', 'Constancia de Capacitación'), ('otro', 'Otro')], max_length=30)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='expedientes/%Y/%m/')),
                ('tipo_archivo', models.CharField(max_length=20)),
                ('tamaño_bytes', models.PositiveIntegerField(default=0)),
                ('contenido_texto', models.TextField(blank=True)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('folio', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('notas_revision', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='empleados.empleado')),
                ('incidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_soporte', to='nomina.incidencianomina')),
                ('mensaje_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_adjuntos', to='chat.mensaje')),
                ('recibo_nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_soporte', to='nomina.recibonomina')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Expediente',
                'verbose_name_plural': 'Documentos de Expediente',
                'db_table': 'empleados_documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
