# Generated by Django 5.1.2 on 2025-12-01 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComandoIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intencion', models.CharField(max_length=100)),
                ('parametros', models.JSONField(default=dict)),
                ('endpoint_api', models.CharField(blank=True, max_length=200)),
                ('metodo_http', models.CharField(blank=True, max_length=10)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutado', 'Ejecutado'), ('error', 'Error'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('respuesta', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Comando IA',
                'verbose_name_plural': 'Comandos IA',
                'db_table': 'chat_comandos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modelo', models.CharField(default='claude-sonnet-4-20250514', max_length=50)),
                ('temperatura', models.FloatField(default=0.3)),
                ('max_tokens', models.IntegerField(default=4096)),
                ('nombre_asistente', models.CharField(default='Asistente RRHH', max_length=50)),
                ('instrucciones_personalizadas', models.TextField(blank=True)),
                ('mensajes_por_dia_empleado', models.IntegerField(default=50)),
                ('mensajes_por_dia_empleador', models.IntegerField(default=500)),
                ('puede_crear_entidades', models.BooleanField(default=True)),
                ('puede_modificar_entidades', models.BooleanField(default=True)),
                ('puede_eliminar_entidades', models.BooleanField(default=False)),
                ('puede_procesar_nomina', models.BooleanField(default=True)),
                ('puede_leer_documentos', models.BooleanField(default=True)),
                ('puede_generar_documentos', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración IA',
                'verbose_name_plural': 'Configuraciones IA',
                'db_table': 'chat_configuracion',
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'db_table': 'chat_conversaciones',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], max_length=20)),
                ('contenido', models.TextField()),
                ('accion_ejecutada', models.CharField(choices=[('ninguna', 'Ninguna'), ('crear', 'Crear'), ('leer', 'Leer'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar'), ('calcular', 'Calcular'), ('generar', 'Generar documento')], default='ninguna', max_length=20)),
                ('entidad_afectada', models.CharField(blank=True, max_length=50)),
                ('id_entidad', models.IntegerField(blank=True, null=True)),
                ('resultado_accion', models.JSONField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='chat/adjuntos/%Y/%m/')),
                ('tipo_archivo', models.CharField(blank=True, max_length=50)),
                ('datos_extraidos', models.JSONField(blank=True, null=True)),
                ('tokens_entrada', models.IntegerField(default=0)),
                ('tokens_salida', models.IntegerField(default=0)),
                ('tiempo_respuesta_ms', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'chat_mensajes',
                'ordering': ['created_at'],
            },
        ),
    ]
