# Generated by Django 5.1.2 on 2025-12-01 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('empleados', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionia',
            name='empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_ia', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='empleado_contexto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='empresa_contexto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='empresas.empresa'),
        ),
    ]
