# Generated by Django 5.1.2 on 2025-12-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='datos_flujo',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='flujo_activo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='paso_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='archivo_contenido_texto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='archivo_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
