# Generated by Django 5.1.2 on 2025-12-02 12:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_initial'),
        ('empresas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('politica', 'Política'), ('reglamento', 'Reglamento'), ('manual', 'Manual'), ('procedimiento', 'Procedimiento'), ('formato', 'Formato'), ('contrato_plantilla', 'Plantilla de Contrato'), ('comunicado', 'Comunicado'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('archivo', models.FileField(upload_to='documentos_rag/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'txt'])])),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('tamaño_bytes', models.PositiveBigIntegerField(default=0)),
                ('contenido_texto', models.TextField(blank=True, help_text='Texto extraído del documento')),
                ('tipo_acceso', models.CharField(choices=[('publico', 'Público (todos)'), ('empresa', 'Empresa (empleados de la empresa)'), ('rrhh', 'Solo RRHH/Admin'), ('privado', 'Privado (solo quien subió)')], default='empresa', max_length=20)),
                ('procesado', models.BooleanField(default=False)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('error_procesamiento', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, help_text='Ej: v1.0, 2024-01', max_length=20)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Tags separados por coma', max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_rag', to='empresas.empresa')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento RAG',
                'verbose_name_plural': 'Documentos RAG',
                'db_table': 'documentos_rag',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FragmentoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenido', models.TextField()),
                ('numero_fragmento', models.PositiveIntegerField(default=0)),
                ('pagina', models.PositiveIntegerField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding del fragmento', null=True)),
                ('num_tokens', models.PositiveIntegerField(default=0)),
                ('num_caracteres', models.PositiveIntegerField(default=0)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='documentos.documento')),
            ],
            options={
                'verbose_name': 'Fragmento de Documento',
                'verbose_name_plural': 'Fragmentos de Documentos',
                'db_table': 'fragmentos_documento',
                'ordering': ['documento', 'numero_fragmento'],
            },
        ),
    ]
